server:
  port: 8081
  servlet:
    context-path: /demo
spring:
  datasource:
    url: jdbc:mysql://116.196.119.6:3306/demo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true